name = "PaddleBattle"
uuid = "ab387484-9d4f-11e9-295c-bbaebd14eb18"
authors = ["Nathan Daly <nhdaly@gmail.com>"]
version = "1.1.0"

[deps]
SimpleDirectMediaLayer = "98e33af6-2ee5-5afd-9e75-cbc738b767c4"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
